# Generated by Django 3.2.25 on 2025-02-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolarisUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('photo_id_front', models.ImageField(blank=True, null=True, upload_to='photos/front/')),
                ('photo_id_back', models.ImageField(blank=True, null=True, upload_to='photos/back/')),
            ],
        ),
    ]
